# Generated by Django 4.0 on 2021-12-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255, unique=True)),
                ('c_email', models.CharField(max_length=255, unique=True)),
                ('c_email_1', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('c_email_2', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('c_phone', models.CharField(max_length=30)),
                ('c_phone1', models.CharField(blank=True, max_length=30, null=True)),
                ('c_phone2', models.CharField(blank=True, max_length=30, null=True)),
                ('c_address', models.CharField(max_length=30)),
                ('c_logo', models.ImageField(blank=True, null=True, upload_to='logo')),
            ],
        ),
    ]
