# Generated by Django 4.0 on 2021-12-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='c_meta_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='c_meta_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
